### ISSUE TITLE
Wine crash pendant le patch

### ISSUE THREAD

**Issue by hyultis** [Noxalus/KHFM-VF-Patch#10]
Salut,

Je suis sous linux (kubuntu 24.04) et j'essaie d'installer le patch sur la version steam du jeu.

Mais je tombe sur cette erreur : 
```
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
0138:err:eventlog:ReportEventW L"Application: KHFM-VF-Patch.exe\n"
0138:err:eventlog:ReportEventW L"CoreCLR Version: 5.0.1422.5710\n"
0138:err:eventlog:ReportEventW L".NET Version: 5.0.14\n"
0138:err:eventlog:ReportEventW L"Description: The process was terminated due to an unhandled exception.\n"
0138:err:eventlog:ReportEventW L"Exception Info: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.\n"
wine: Unhandled exception 0x00000000 in thread 138 at address 7BD33050 (thread 0138), starting debugger...
```

J'ai vue qu'une autre issue indiquait une différence entre 32/64 bits, mais ça ne change pas grand chose de mon coté : (en wine 32bits)

```
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at KHFM_VF_Patch.App.Main()
0024:err:eventlog:ReportEventW L"Application: KHFM-VF-Patch.exe\n"
0024:err:eventlog:ReportEventW L"CoreCLR Version: 5.0.1422.5710\n"
0024:err:eventlog:ReportEventW L".NET Version: 5.0.14\n"
0024:err:eventlog:ReportEventW L"Description: The process was terminated due to an unhandled exception.\n"
0024:err:eventlog:ReportEventW L"Exception Info: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.\r\n"
0024:err:eventlog:ReportEventW L"   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Threading.Dispatcher.Run()\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Application.RunDispatcher(Object ignore)\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Application.RunInternal(Window window)\r\n"
0024:err:eventlog:ReportEventW L"   at System.Windows.Application.Run()\r\n"
0024:err:eventlog:ReportEventW L"   at KHFM_VF_Patch.App.Main()\n"
wine: Unhandled exception 0x00000000 in thread 24 at address 7BD33050 (thread 0024), starting debugger...
```

Edit : je précise, mais j'ai 200Go d'espace libre.

Merci

**Comment by Noxalus** [comment]
Salut !

Merci pour l'info, je n'ai jamais tenté de lancer le patch sous Linux (avec Wine) et même avec la stacktrace j'ai un peu de mal à voir ce qu'il se passe vraiment. Il faut que je creuse en faisant des tests de mon côté sur une VM.

Sur la différence de la version 32 ou 64 bits, je viens de vérifier, mais si à l'époque on avait les 2 versions différentes, aujourd'hui seule la version 32 bits est générée (ce qui du coup ne devrait pas être un problème).

**Comment by hyultis** [comment]
Np, si tu as besoin que je fasse des tests hésite pas.

J'ai mis une petite vidéo du patcher, il a l'air de planter sur l'étape "KH1FM-Voices.patch"

https://github.com/Noxalus/KHFM-VF-Patch/assets/11379458/e2282bb0-4479-4d6c-a2b1-026611a5c534

Si ça peut aider, voici le retour du debugger de wine : 

```
Couldn't get first exception for process 0020 Z:\mnt\games\SteamLibrary\steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-\khpatchs\KHFM-VF-Patch-1.2.2\KHFM-VF-Patch.exe (WOW64).
No backtrace available
Modules:
Module  Address                 Debug info      Name (213 modules)
PE        400000-  43a000       Deferred        khfm-vf-patch
PE       5fd0000- 6042000       Deferred        khfm-vf-patch
PE       60f0000- 60fa000       Deferred        system.runtime
PE       6100000- 6234000       Deferred        system.xaml
PE       69e0000- 69fc000       Deferred        netstandard
PE       6a10000- 6a49000       Deferred        system.private.uri
PE       6a50000- 71f7000       Deferred        presentationcore
PE       7280000- 72f3000       Deferred        directwriteforwarder
PE       7310000- 7314000       Deferred        system.runtime.extensions
PE       7320000- 732c000       Deferred        system.runtime.interopservices
PE       7330000- 7335000       Deferred        system.runtime.compilerservices.visualc
PE       7350000- 7354000       Deferred        system.diagnostics.debug
PE       7360000- 7372000       Deferred        system.threading
PE       7390000- 7396000       Deferred        microsoft.win32.primitives
PE       73a0000- 73b5000       Deferred        system.collections.nongeneric
PE       73c0000- 741b000       Deferred        system.linq
PE       7430000- 746e000       Deferred        system.collections
PE       7490000- 74a3000       Deferred        microsoft.win32.registry
PE       74b0000- 74c4000       Deferred        system.collections.specialized
PE       7810000- 781a000       Deferred        system.io.filesystem.driveinfo
PE       7850000- 785e000       Deferred        system.componentmodel.primitives
PE       7b20000- 7b3c000       Deferred        system.drawing.primitives
PE       7b70000- 7b74000       Deferred        system.threading.thread
PE       7b90000- 7c62000       Deferred        system.configuration.configurationmanager
PE       7c80000- 7c85000       Deferred        system.xml.readerwriter
PE       7c90000- 83c8000       Deferred        system.private.xml
PE       8400000- 842f000       Deferred        system.io.filesystem
PE       8430000- 8452000       Deferred        system.net.webclient
PE       8480000- 84b0000       Deferred        system.memory
PE       84c0000- 8556000       Deferred        system.security.cryptography.algorithms
PE       8560000- 8564000       Deferred        system.text.encoding.extensions
PE       85b0000- 85b5000       Deferred        system.componentmodel
PE       85c0000- 85da000       Deferred        system.diagnostics.tracesource
PE       85f0000- 8689000       Deferred        system.componentmodel.typeconverter
PE       86a0000- 86b1000       Deferred        system.windows.extensions
PE       86d0000- 86d4000       Deferred        system.threading.threadpool
PE       86e0000- 86f4000       Deferred        system.objectmodel
PE       8710000- 873b000       Deferred        system.collections.concurrent
PE       97a0000- 97e2000       Deferred        uiautomationtypes
PE       9c00000- 9c4b000       Deferred        system.net.requests
PE       9c50000- 9c7e000       Deferred        system.net.primitives
PE       9c80000- 9c8e000       Deferred        system.net.webheadercollection
PE       9f60000- 9f6c000       Deferred        uiautomationprovider
PE       9f70000- 9fab000       Deferred        system.diagnostics.process
PE       a000000- a041000       Deferred        presentationframework.classic
PE       a080000- a084000       Deferred        system.resources.resourcemanager
PE       a4b0000- a4d0000       Deferred        presentationcore.resources
PE       b0e0000- b0e6000       Deferred        presentationframework-systemxml
PE       c1d0000- c276000       Deferred        system.windows.forms.primitives
PE       d330000- dea6000       Deferred        system.windows.forms
PE       df60000- dfa2000       Deferred        dotnetzip
PE       ed40000- ee0f000       Deferred        system.text.encoding.codepages
PE       ee10000- ee82000       Deferred        system.text.regularexpressions
PE      10000000-10012000       Deferred        mscorlib
PE      10030000-1006d000       Deferred        system.io.packaging
PE      10110000-102f7000       Deferred        windowsbase
PE      105c0000-113e5000       Deferred        presentationframework
PE-Wine 1e940000-1e955000       Deferred        msimg32
PE-Wine 1e960000-1e9bb000       Deferred        explorerframe
PE-Wine 1e9c0000-1e9e4000       Deferred        compstui
PE-Wine 1e9f0000-1ea90000       Deferred        winspool
PE-Wine 1ea90000-1ef37000       Deferred        comctl32
PE-Wine 1ef40000-1f180000       Deferred        comdlg32
PE-Wine 1f180000-1f23c000       Deferred        oleacc
PE-Wine 1f240000-1f39b000       Deferred        uiautomationcore
PE-Wine 1f3a0000-1f3c8000       Deferred        wtsapi32
PE-Wine 1f3d0000-1f437000       Deferred        propsys
PE-Wine 1f440000-1fae7000       Deferred        windowscodecs
PE-Wine 1faf0000-1fb7b000       Deferred        ws2_32
PE-Wine 1fb80000-1fbd4000       Deferred        mpr
PE-Wine 1fbe0000-1fd8e000       Deferred        wininet
PE-Wine 1fd90000-1fffd000       Deferred        urlmon
PE      31000000-3182f000       Deferred        system.private.corelib
ELF     5482d000-54858000       Deferred        libgpg-error.so.0
ELF     54858000-54965000       Deferred        libgcrypt.so.20
ELF     54965000-54a4c000       Deferred        libsystemd.so.0
ELF     54a4c000-54aac000       Deferred        libdbus-1.so.3
ELF     54aac000-54b88000       Deferred        libkrb5.so.3
ELF     54f8e000-54fb4000       Deferred        liblz4.so.1
ELF     54fb4000-5500f000       Deferred        libgssapi_krb5.so.2
ELF     5500f000-550bb000       Deferred        libcups.so.2
ELF     6145b000-61460000       Deferred        <wine-loader>
ELF     6270e000-6273e000       Deferred        libk5crypto.so.3
ELF     63e3e000-64aa1000       Deferred        libnvidia-glvkspirv.so.555.52.04
ELF     64aa1000-67f62000       Deferred        libnvidia-gpucomp.so.555.52.04
ELF     67f62000-69c88000       Deferred        libnvidia-glcore.so.555.52.04
ELF     69c88000-6aaad000       Deferred        libvulkan_intel_hasvk.so
ELF     6aaad000-6bb22000       Deferred        libvulkan_intel.so
ELF     6bb22000-6d882000       Deferred        libicudata.so.74
ELF     6d882000-75dc0000       Deferred        libllvm-17.so.1
PE-Wine 75dc0000-75f3f000       Deferred        setupapi
PE-Wine 75f50000-763c3000       Deferred        opengl32
PE-Wine 763e0000-77709000       Deferred        wined3d
PE-Wine 77720000-77876000       Deferred        d3d9
PE-Wine 77890000-778ae000       Deferred        dwmapi
PE      778c0000-77c54000       Deferred        d3dcompiler_47_cor3
PE      77c70000-77e2a000       Deferred        wpfgfx_cor3
PE      77e40000-77f26000       Deferred        presentationnative_cor3
PE-Wine 77f40000-77f87000       Deferred        bcrypt
PE-Wine 77fa0000-7822d000       Deferred        dwrite
PE-Wine 78240000-7849a000       Deferred        dbghelp
PE-Wine 784b0000-7857a000       Deferred        mscoree
PE-Wine 78590000-78635000       Deferred        uxtheme
PE-Wine 78650000-7869c000       Deferred        winex11
PE      786b0000-787bb000       Deferred        clrjit
PE-Wine 787d0000-78b8c000       Deferred        oleaut32
PE-Wine 78ba0000-78be1000       Deferred        coml2
PE-Wine 78c00000-78e11000       Deferred        rpcrt4
PE-Wine 78e30000-78f72000       Deferred        combase
PE-Wine 78f90000-793cd000       Deferred        ole32
PE      793e0000-797f9000       Deferred        coreclr
PE      79810000-79850000       Deferred        hostpolicy
PE      79860000-798a0000       Deferred        hostfxr
PE-Wine 798b0000-79913000       Deferred        imm32
PE-Wine 79930000-79971000       Deferred        shcore
PE-Wine 79990000-79a76000       Deferred        shlwapi
ELF     79a83000-79a90000       Deferred        libcap.so.2
PE-Wine 79a90000-7a70e000       Deferred        shell32
ELF     7a70e000-7a720000       Deferred        libresolv.so.2
PE-Wine 7a720000-7a757000       Deferred        win32u
ELF     7a75a000-7a770000       Deferred        libavahi-client.so.3
PE-Wine 7a770000-7a9b0000       Deferred        gdi32
ELF     7a9b1000-7a9c0000       Deferred        libkrb5support.so.0
PE-Wine 7a9c0000-7accf000       Deferred        ucrtbase
ELF     7acd1000-7ace0000       Deferred        libavahi-common.so.3
PE-Wine 7ace0000-7ad6b000       Deferred        sechost
PE-Wine 7ad80000-7ae6c000       Deferred        advapi32
PE-Wine 7ae80000-7b119000       Deferred        msvcrt
PE-Wine 7b130000-7b15a000       Deferred        zlib1
PE-Wine 7b170000-7b637000       Deferred        user32
PE-Wine 7b650000-7bb7b000       Deferred        kernelbase
PE-Wine 7bb90000-7bcf7000       Deferred        kernel32
PE-Wine 7bd10000-7bfee000       Deferred        ntdll
ELF     7bfef000-7bff6000       Deferred        libkeyutils.so.1
ELF     7c0e5000-7c0ea000       Deferred        libcom_err.so.2
ELF     7c0ea000-7c0f0000       Deferred        winspool.so
ELF     7c548000-7c584000       Deferred        libglx.so.0
ELF     7c584000-7c600000       Deferred        libgldispatch.so.0
ELF     7c72a000-7c796000       Deferred        libgl.so.1
ELF     7c7b4000-7c7d2000       Deferred        libxcb-glx.so.0
ELF     7c7d9000-7c7eb000       Deferred        libvklayer_mesa_device_select.so
ELF     7c7eb000-7c7f0000       Deferred        libpthread.so.0
ELF     7c7f0000-7c7f5000       Deferred        libdl.so.2
ELF     7c7f5000-7c7fc000       Deferred        libnvidia-tls.so.555.52.04
ELF     7c7fc000-7c8c2000       Deferred        libnvidia-glsi.so.555.52.04
ELF     7c8c2000-7c9f3000       Deferred        libglx_nvidia.so.0
ELF     7c9f3000-7cb2f000       Deferred        libvulkan_virtio.so
ELF     7cb2f000-7d3cc000       Deferred        libvulkan_lvp.so
ELF     7d3cc000-7d3e6000       Deferred        libdrm.so.2
ELF     7d40b000-7d441000       Deferred        liblzma.so.5
ELF     7d441000-7d65a000       Deferred        libicuuc.so.74
ELF     7d65a000-7d82f000       Deferred        libxml2.so.2
ELF     7d82f000-7d85d000       Deferred        libtinfo.so.6
ELF     7d85d000-7d895000       Deferred        libedit.so.2
ELF     7d895000-7d89d000       Deferred        libatomic.so.1
ELF     7db1f000-7db3f000       Deferred        libelf.so.1
ELF     7db3f000-7dbfc000       Deferred        libzstd.so.1
ELF     7dbfc000-7e6ca000       Deferred        libvulkan_radeon.so
ELF     7e6ca000-7e75f000       Deferred        libvulkan.so.1
ELF     7e75f000-7e800000       Deferred        opengl32.so
ELF     7e904000-7e917000       Deferred        libxcb-randr.so.0
ELF     7e91b000-7e920000       Deferred        libxshmfence.so.1
ELF     7e920000-7e925000       Deferred        libxcb-shm.so.0
ELF     7e925000-7e930000       Deferred        libxcb-xfixes.so.0
ELF     7e930000-7e935000       Deferred        libx11-xcb.so.1
ELF     7e936000-7e93f000       Deferred        libxcb-sync.so.1
ELF     7e93f000-7e944000       Deferred        libxcb-present.so.0
ELF     7e944000-7e94b000       Deferred        libxcb-dri3.so.0
ELF     7e94b000-7e95a000       Deferred        libwayland-client.so.0
ELF     7e95c000-7e962000       Deferred        ws2_32.so
ELF     7e978000-7ea09000       Deferred        libgmp.so.10
ELF     7ea09000-7ea52000       Deferred        libhogweed.so.6
ELF     7ea52000-7eaa5000       Deferred        libnettle.so.8
ELF     7eaa5000-7eabc000       Deferred        libtasn1.so.6
ELF     7eabc000-7ec69000       Deferred        libunistring.so.5
ELF     7ec69000-7ec9d000       Deferred        libidn2.so.0
ELF     7ec9d000-7ee6b000       Deferred        libp11-kit.so.0
ELF     7ee6b000-7f0ac000       Deferred        libgnutls.so.30
ELF     7f0ad000-7f0b2000       Deferred        librt.so.1
ELF     7f0b6000-7f0c3000       Deferred        libdrm_amdgpu.so.1
ELF     7f0ee000-7f0f6000       Deferred        libxfixes.so.3
ELF     7f0f6000-7f103000       Deferred        libxcursor.so.1
ELF     7f103000-7f118000       Deferred        libxi.so.6
ELF     7f118000-7f11d000       Deferred        libxcomposite.so.1
ELF     7f11d000-7f12c000       Deferred        libxrandr.so.2
ELF     7f12c000-7f13a000       Deferred        libxrender.so.1
ELF     7f13a000-7f142000       Deferred        libxxf86vm.so.1
ELF     7f142000-7f154000       Deferred        libmd.so.0
ELF     7f154000-7f16a000       Deferred        libbsd.so.0
ELF     7f16a000-7f198000       Deferred        libxcb.so.1
ELF     7f198000-7f2ea000       Deferred        libx11.so.6
ELF     7f2ea000-7f300000       Deferred        libxext.so.6
ELF     7f504000-7f509000       Deferred        libxinerama.so.1
ELF     7f509000-7f510000       Deferred        libxdmcp.so.6
ELF     7f510000-7f59a000       Deferred        winex11.so
ELF     7f59a000-7f5d2000       Deferred        libgcc_s.so.1
ELF     7f5d2000-7f5dd000       Deferred        libffi.so.8
ELF     7f5dd000-7f5ea000       Deferred        bcrypt.so
ELF     7f5ea000-7f5f0000       Deferred        dwrite.so
ELF     7f6cd000-7f6f9000       Deferred        libexpat.so.1
ELF     7f6f9000-7f74d000       Deferred        libfontconfig.so.1
ELF     7f74d000-7f770000       Deferred        libbrotlicommon.so.1
ELF     7f770000-7f77e000       Deferred        libbrotlidec.so.1
ELF     7f77e000-7f7bb000       Deferred        libpng16.so.16
ELF     7f7bb000-7f7cd000       Deferred        libbz2.so.1.0
ELF     7f7cd000-7f7e9000       Deferred        libz.so.1
ELF     7f7e9000-7f8bd000       Deferred        libfreetype.so.6
ELF     7f8bd000-7f9c7000       Deferred        libm.so.6
ELF     7f9c7000-7f9cc000       Deferred        libxau.so.6
ELF     7f9e5000-7fb68000       Deferred        win32u.so
ELF     ee237000-ee2ec000       Export          ntdll.so
ELF     ee2ec000-ee528000       Deferred        libc.so.6
ELF     ee54e000-ee583000       Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 (D) Z:\mnt\games\SteamLibrary\steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-\khpatchs\KHFM-VF-Patch-1.2.2\KHFM-VF-Patch.exe
	00000024    0     
	00000118    0     
	0000011c    0     
	00000120    2     .NET Finalizer
	00000124    0     .NET Timer
	00000134    0     
	00000138    0     wine_rpcrt4_server
	0000013c    0     wined3d_cs
	00000140    0     wined3d_cs
	0000014c    0     wined3d_cs
	00000180    0     .NET ThreadPool Worker
	0000019c    0     .NET ThreadPool Worker
	000001a4    0     .NET ThreadPool Worker
	000001a8    0     .NET ThreadPool Worker
	000001ac    0     .NET ThreadPool Worker
	000001b8    0     .NET ThreadPool Gate
	000001cc    0 <== 
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000078    0     wine_rpcrt4_io
	00000098    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000cc    0     wine_rpcrt4_io
	000000e0    0     
	000000f8    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000d8    0     
	000000dc    0     
00000068 winedevice.exe
	0000006c    0     
	0000007c    0     
	00000080    0     wine_sechost_service
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
	00000094    0     
	000000a4    0     
	000000a8    0     
	000000ac    0     
	000000b0    0     
00000070 explorer.exe
	00000074    0     
	000000e4    0     
	000000e8    0     wine_rpcrt4_server
0000009c plugplay.exe
	000000a0    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
	000000c0    0     wine_rpcrt4_server
000000c4 svchost.exe
	000000c8    0     
	000000d0    0     
	000000d4    0     wine_sechost_service
000000f0 rpcss.exe
	000000f4    0     
	00000100    0     
	00000104    0     wine_sechost_service
	00000108    0     wine_rpcrt4_server
	0000010c    0     wine_rpcrt4_server
	00000110    0     wine_rpcrt4_io
000001c4 conhost.exe
	000001c8    0     
System information:
    Wine build: wine-9.0 (Ubuntu 9.0~repack-4build3)
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 6.8.0-35-generic
```

**Comment by Noxalus** [comment]
Merci beaucoup pour les détails ! 🙏 

Malheureusement, j'ai toujours un peu de mal à savoir ce qu'il se passe sans pouvoir faire de tests côté code :/

Je vais essayer de reproduire l'erreur de mon côté sur une VM, je te tiens au courant 👍

**Comment by Noxalus** [comment]
![image](https://github.com/Noxalus/KHFM-VF-Patch/assets/1321964/e6501c59-d696-4c22-9d96-2a2b142dec40)

Comment as-tu fait pour installer le jeu sur Kubuntu depuis Steam ? Tu as installé la version Windows de Steam avec Wine ? @hyultis 🤔 

EDIT: C'est bon, je n'ai pas l'habitude, mais il y a une option de compatibilité qui permet d'installer des jeux normalement jouable que sur Windows (via Proton). 👍

**Comment by Noxalus** [comment]
Désolé pour le délai, je viens tout juste de réussir à utiliser le patch jusqu'au bout sur Kubuntu 24.04 de mon côté (je n'ai pas lancé le jeu en revanche):

https://github.com/Noxalus/KHFM-VF-Patch/assets/1321964/41c59dfb-85c6-438e-90dc-c61a887e0234

Du coup il y a forcément quelque chose de spécifique sur ta machine qui semble poser problème, mais cela va rendre le debug compliqué 😓

**Comment by hyultis** [comment]
Merci pour ton retour, en refaisant un test, je viens de voir que j'avais la version de .NET en "5.0.14", en utilisant la dernière version "5.0.17", et ça fonctionne !

Désoler de t'avoir fait perdre du temps ><', et merci !

**Comment by Noxalus** [comment]
Pas de problème, c'est une info que je prends ! 🙏 

Content que tu aies pu trouver une solution au problème en tout cas ! 👌
